version: 2
updates:
  # update GH actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directories: 
      - "Azure Functions/*"
    schedule:
      interval: "weekly"
